// Re-export the supabase client and types for easy importing
export { supabase } from './client';
export type { 
  Database,
  Contact,
  ContactInsert,
  ContactUpdate,
  Conversation,
  ConversationInsert,
  ConversationUpdate,
  BulkCampaign,
  BulkCampaignInsert,
  BulkCampaignUpdate,
  MessageResult,
  MessageResultInsert,
  MessageResultUpdate,
  LeadDetail,
  LeadDetailInsert,
  LeadDetailUpdate,
  LeadRequirement,
  LeadRequirementInsert,
  LeadRequirementUpdate,
  LeadDocument,
  LeadDocumentInsert,
  LeadDocumentUpdate,
  LeadInteraction,
  LeadInteractionInsert,
  LeadInteractionUpdate,
  ContactList,
  ContactListInsert,
  ContactListUpdate,
  ContactListMembership,
  ContactListMembershipInsert,
  ContactListMembershipUpdate,
  LeadSummary,
  LeadSource,
  LeadStatus,
  ContactMethod,
  Priority,
  RequirementStatus,
  InteractionType,
  CampaignStatus,
  MessageStatus
} from './types';
